version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - SERVERURL=auto  # The WireGuard server will automatically detect its external IP
      - SERVERPORT=51820  # Port to run WireGuard on
      - PEERS=3  # Creates 3 client configs named peer1, peer2, peer3
      - PEERDNS=1.1.1.1,1.0.0.1  # Using Cloudflare DNS
      - INTERNAL_SUBNET=10.13.13.0/24  # Internal WireGuard network
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
